const data = {
  products: [
    {
      name: 'Nike Slim Short',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      conuntInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      newReviews: 14,
      description: 'hight quality product',
    },
    {
      name: 'Under Armour Fit Pant',
      slug: 'under-armour-fit-pant',
      category: 'Pants',
      image: '/images/p2.jpg',
      price: 65,
      conuntInStock: 5,
      brand: 'Under Armour',
      rating: 4.5,
      newReviews: 10,
      description: 'hight quality product',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p2.jpg',
      price: 65,
      conuntInStock: 5,
      brand: 'Adidas',
      rating: 4.5,
      newReviews: 10,
      description: 'hight quality product',
    },
    {
      name: 'Puma Fit Pant',
      slug: 'puma-fit-pant',
      category: 'Pants',
      image: '/images/p2.jpg',
      price: 65,
      conuntInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      newReviews: 10,
      description: 'hight quality product',
    },
  ],
};

export default data;
